'use strict';

// Exercises the production-heightfield renderer with controlled, overlapping
// existing assets. It does not add a gameplay route or runtime test surface.
const assert = require('assert');
const fs = require('fs');
const http = require('http');
const path = require('path');
const { chromium } = require('playwright');

const root = path.resolve(__dirname, '..');
const artifact = path.join(root, 'index.html');
const outputArg = process.argv.find((arg) => arg.startsWith('--output='));
const output = path.resolve(root, outputArg ? outputArg.slice('--output='.length) : path.join('test-results', 'billboard-opacity-occlusion', 'billboard-overlap.json'));
function assertOutputPath(target) { const evidence = path.join(root, 'test-results'); const relative = path.relative(evidence, target); assert(relative && !relative.startsWith(`..${path.sep}`) && !path.isAbsolute(relative), 'output must stay below ignored test-results'); }
function serve(html) { return new Promise((resolve, reject) => { const server = http.createServer((request, response) => { const pathname = new URL(request.url, 'http://127.0.0.1').pathname; if(pathname === '/' || pathname === '/index.html') { response.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' }); response.end(html); return; } response.writeHead(404); response.end('not found'); }); server.once('error', reject); server.listen(0, '127.0.0.1', () => resolve({ server, url: `http://127.0.0.1:${server.address().port}/` })); }); }

async function main() {
  assertOutputPath(output); fs.mkdirSync(path.dirname(output), { recursive: true });
  const result = { pass: false, cases: [], screenshots: [], observed: { consoleErrors: [], pageErrors: [], externalRequests: [] }, checks: {}, errors: [] };
  let server, browser, context, page;
  try {
    ({ server, url: result.url } = await serve(fs.readFileSync(artifact, 'utf8')));
    browser = await chromium.launch(); context = await browser.newContext({ viewport: { width: 400, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 }); page = await context.newPage();
    const origin = new URL(result.url).origin;
    page.on('console', (message) => { if(message.type() === 'error') result.observed.consoleErrors.push(message.text()); });
    page.on('pageerror', (error) => result.observed.pageErrors.push(String(error.stack || error)));
    page.on('request', (request) => { if(/^https?:/i.test(request.url()) && new URL(request.url()).origin !== origin) result.observed.externalRequests.push(request.url()); });
    await page.goto(result.url + '?mobile=on&portraitlayout=1', { waitUntil: 'load' });
    await page.locator('[data-action="title-start"]').click(); await page.waitForSelector('#cronboardok', { state: 'visible' }); await page.locator('#cronboardok').click();
    await page.waitForFunction(() => Object.values(window.SNC_RUNTIME_SIGN_ASSET_REGISTRY || {}).length === 5 && Object.values(window.SNC_RUNTIME_SIGN_ASSET_REGISTRY).every((entry) => entry.image.complete && entry.image.naturalWidth > 0) && Object.values(window.SNC_RUNTIME_ASSET_REGISTRY || {}).every((entry) => entry.image.complete && entry.image.naturalWidth > 0));
    result.cases = await page.evaluate(() => {
      const signIds = ['sign_summer_loop_market_001', 'sign_snc_can_station_001', 'sign_drop_off_cans_001', 'sign_neighbor_1_can_001', 'sign_family_3_cans_001'];
      const backgrounds = ['billboard', 'npc', 'can', 'planter', 'wall'];
      const saved = { x: player.x, y: player.y, angle: player.angle, props: game.props, npcs: game.npcs, pickups: game.pickups, map: game.map.map((row) => row.slice()), profiles: game.verticalProfileGrid.slice(), rotations: game.verticalProfileRotationGrid.slice() };
      const samePixel = (left, right, index) => left[index] === right[index] && left[index + 1] === right[index + 1] && left[index + 2] === right[index + 2] && left[index + 3] === right[index + 3];
      function render(){ drawScene(0, { x: player.x, y: player.y, angle: player.angle }); return bctx.getImageData(0, 0, RW, RH).data; }
      function reset(){ player.x = 24.5; player.y = 16.0; player.angle = -Math.PI / 2; game.props = []; game.npcs = []; game.pickups = []; game.map = saved.map.map((row) => row.slice()); game.verticalProfileGrid = saved.profiles.slice(); game.verticalProfileRotationGrid = saved.rotations.slice(); }
      function addWorldBackdrop(background){ if(background === 'planter') { game.map[10][24] = WALL.CONCRETE; game.verticalProfileGrid[10 * game.MAP_W + 24] = 3; game.verticalProfileRotationGrid[10 * game.MAP_W + 24] = 0; } if(background === 'wall') { game.map[8][24] = WALL.CONCRETE; game.verticalProfileGrid[8 * game.MAP_W + 24] = CR_VERTICAL_PROFILE_IDS.FULL_LEGACY; } }
      function addSpriteBackdrop(background){ if(background === 'billboard') game.props.push({ x: 24.5, y: 9.2, kind: 'signboard', assetId: 'sign_neighbor_1_can_001', signSizeClass: 'standard', wob: 0 }); if(background === 'npc') game.npcs.push({ x: 24.5, y: 9.5, kind: 'hungry', assetId: 'npc_unhoused_work_jacket_001', helped: false, wob: 0 }); if(background === 'can') game.pickups.push({ x: 24.5, y: 10.1, amt: 1, taken: false, wob: 0 }); }
      function coverage(front){ const tex = propTex(front.kind, front), hp = crHeightfieldSpriteWorldHeight('prop', front); const dirX = Math.cos(player.angle), dirY = Math.sin(player.angle), planeX = -Math.sin(player.angle) * cfg.fov, planeY = Math.cos(player.angle) * cfg.fov; const invDet = 1 / (planeX * dirY - dirX * planeY), rx = front.x - player.x, ry = front.y - player.y, depth = invDet * (-planeY * rx + planeX * ry), hscr = invDet * (dirY * rx - dirX * ry); const bounds = crHeightfieldPhysicalSpriteBounds('prop', front, tex, hp), projection = crProjectHeightfieldVisibleSprite(front, tex, hp, depth, hscr, bounds); const covered = new Set(); for(let col = Math.max(0, Math.floor(projection.screenLeft)); col < Math.min(RW, Math.ceil(projection.screenLeft + projection.screenW)); col++) { const u = (col - projection.screenLeft) / projection.screenW, sourceX = Math.max(projection.sourceX, Math.min(projection.sourceX + projection.sourceWidth - 1, (projection.sourceX + u * projection.sourceWidth) | 0)); for(let y = Math.max(0, Math.floor(projection.topY)); y < Math.min(RH, Math.ceil(projection.bottomY)); y++) { const sourceY = Math.max(projection.sourceY, Math.min(projection.sourceY + projection.sourceHeight - 1, (projection.sourceY + (y - projection.topY) / projection.screenH * projection.sourceHeight) | 0)); if(crHeightfieldSpriteOpaqueAt(tex, sourceX, sourceY)) covered.add(y * RW + col); } } return covered; }
      const rows = [];
      try { for(const assetId of signIds) for(const background of backgrounds) { reset(); const original = render(); addWorldBackdrop(background); const worldOnly = render(); addSpriteBackdrop(background); const backgroundOnly = render(); const front = { x: 24.5, y: 12.0, kind: 'signboard', assetId, signSizeClass: SNC_RUNTIME_SIGN_ASSET_REGISTRY[assetId].defaultDisplayClass, wob: 0 }; game.props = [front]; const frontOnly = render(); addSpriteBackdrop(background); const combined = render(); const covered = coverage(front); let backdropPixels = 0, overlapPixels = 0, leakPixels = 0, exteriorBackdropPixels = 0; for(let pixel = 0; pixel < RW * RH; pixel++) { const offset = pixel * 4; const backgroundChanged = !samePixel(background === 'planter' || background === 'wall' ? original : worldOnly, backgroundOnly, offset); if(!backgroundChanged) continue; backdropPixels++; if(covered.has(pixel)) { overlapPixels++; if(!samePixel(frontOnly, combined, offset)) leakPixels++; } else exteriorBackdropPixels++; } rows.push({ assetId, background, backdropPixels, overlapPixels, exteriorBackdropPixels, leakPixels, spriteDepthWrites: crHeightfieldStats.spriteDepthWrites || 0 }); } } finally { player.x = saved.x; player.y = saved.y; player.angle = saved.angle; game.props = saved.props; game.npcs = saved.npcs; game.pickups = saved.pickups; game.map = saved.map; game.verticalProfileGrid = saved.profiles; game.verticalProfileRotationGrid = saved.rotations; }
      return rows;
    });
    for(const [name, assetId, background] of [['01-market-billboard', 'sign_summer_loop_market_001', 'billboard'], ['02-station-npc', 'sign_snc_can_station_001', 'npc'], ['03-drop-off-can', 'sign_drop_off_cans_001', 'can'], ['04-neighbor-planter', 'sign_neighbor_1_can_001', 'planter'], ['05-family-wall', 'sign_family_3_cans_001', 'wall']]) { await page.evaluate(({ assetId: id, background: back }) => { player.x = 24.5; player.y = 16.0; player.angle = -Math.PI / 2; game.props = [{ x: 24.5, y: 12.0, kind: 'signboard', assetId: id, signSizeClass: SNC_RUNTIME_SIGN_ASSET_REGISTRY[id].defaultDisplayClass, wob: 0 }]; game.npcs = []; game.pickups = []; if(back === 'billboard') game.props.push({ x: 24.5, y: 9.2, kind: 'signboard', assetId: 'sign_neighbor_1_can_001', signSizeClass: 'standard', wob: 0 }); if(back === 'npc') game.npcs.push({ x: 24.5, y: 9.5, kind: 'hungry', assetId: 'npc_unhoused_work_jacket_001', helped: false, wob: 0 }); if(back === 'can') game.pickups.push({ x: 24.5, y: 10.1, amt: 1, taken: false, wob: 0 }); if(back === 'planter') { game.map[10][24] = WALL.CONCRETE; game.verticalProfileGrid[10 * game.MAP_W + 24] = 3; } if(back === 'wall') { game.map[8][24] = WALL.CONCRETE; game.verticalProfileGrid[8 * game.MAP_W + 24] = CR_VERTICAL_PROFILE_IDS.FULL_LEGACY; } }, { assetId, background }); await page.waitForTimeout(80); const screenshotPath = path.join(path.dirname(output), `${name}.png`); await page.screenshot({ path: screenshotPath }); result.screenshots.push({ name, file: path.relative(root, screenshotPath).replace(/\\/g, '/') }); }
    result.checks = { exactCaseCount: result.cases.length === 25, allBackdropsOverlap: result.cases.every((row) => row.overlapPixels > 0), opaquePixelsHideBackdrops: result.cases.every((row) => row.leakPixels === 0), transparentExteriorShowsBackdrops: [...new Set(result.cases.map((row) => row.assetId))].every((assetId) => result.cases.some((row) => row.assetId === assetId && row.exteriorBackdropPixels > 0)), spriteDepthWrites: result.cases.every((row) => row.spriteDepthWrites > 0), screenshots: result.screenshots.length === 5, noErrors: result.observed.consoleErrors.length === 0 && result.observed.pageErrors.length === 0 && result.observed.externalRequests.length === 0 };
    result.pass = Object.values(result.checks).every(Boolean);
  } catch(error) { result.errors.push(String(error.stack || error)); }
  finally { for(const resource of [page, context, browser]) if(resource) await resource.close(); if(server) await new Promise((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); }
  if(result.errors.length) result.pass = false; fs.writeFileSync(output, `${JSON.stringify(result, null, 2)}\n`); console.log(JSON.stringify({ pass: result.pass, checks: result.checks, errors: result.errors, output: path.relative(root, output) })); if(!result.pass) process.exitCode = 1;
}
main().catch((error) => { console.error(error.stack || error); process.exitCode = 1; });
