#!/usr/bin/env node
'use strict';

const assert = require('assert');
const childProcess = require('child_process');
const path = require('path');
const buildTool = require('../tools/build-single-file.js');

const ROOT = path.join(__dirname, '..');
const BASELINE = Object.freeze({
  buildId: 'farfieldsmooth1',
  artifactBytes: 1302797,
  artifactSha256: '316fca1b500e4077a3619ee2b1be5e04309fc08c9e14cfe9377bc4be8ebffb82',
  url: 'https://falloutmule.github.io/solidarity-not-charity-can-run/',
});

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function rejects(metadata, expected) {
  try {
    buildTool.validateProjectMetadata(metadata, ROOT);
    return false;
  } catch (error) {
    return String(error.message || error).includes(expected);
  }
}

const metadata = buildTool.loadProjectMetadata(ROOT);
const identity = buildTool.validateProjectMetadata(metadata, ROOT);
const currentCommit = childProcess.execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim();
const artifact = metadata.artifact;
const distribution = metadata.distribution;
const samsung = metadata.acceptance.samsungSmoothness;
const visual = metadata.acceptance.userVisual;
const farField = metadata.selection.farField;

assert.strictEqual(metadata.schemaVersion, 3, 'metadata schema must be version 3');
assert.deepStrictEqual(identity.diagnostics, {
  metadata: BASELINE.buildId,
  source: BASELINE.buildId,
  artifact: BASELINE.buildId,
}, 'metadata, source, and release artifact BUILD_ID values must agree');
assert.deepStrictEqual(artifact, {
  path: 'index.html',
  byteLength: BASELINE.artifactBytes,
  sha256: BASELINE.artifactSha256,
}, 'artifact record must identify the canonical generated bytes');
assert.deepStrictEqual(distribution, {
  provider: 'github-pages',
  url: BASELINE.url,
  source: { branch: 'main', path: '/' },
}, 'distribution record must identify main:/ GitHub Pages publishing');
assert(!Object.prototype.hasOwnProperty.call(metadata.runtime, 'runtimeBaselineCommit'), 'tracked metadata must not embed a stale baseline commit');
assert(!Object.prototype.hasOwnProperty.call(metadata, 'release'), 'tracked metadata must not embed volatile deployment state');
assert(/^[0-9a-f]{40}$/.test(currentCommit), 'CI must derive the current commit from Git');
assert.deepStrictEqual(farField.modes, { ffres: '400', ffangle: 'interp', ffproj: 'subpixel' }, 'selected far-field modes mismatch');
assert.strictEqual(farField.status, 'selected', 'far-field candidate must be recorded as selected');
assert.strictEqual(samsung.status, 'failed', 'Samsung smoothness must remain distinct from publication');
assert.strictEqual(visual.status, 'pending', 'general visual acceptance must not be inferred from publication');
assert(samsung.scope.includes('MOVE plus LOOK'), 'Samsung smoothness scope must name the observed interaction');
assert(visual.scope.includes('No general visual acceptance'), 'visual scope must prevent accidental acceptance inference');

const badArtifact = clone(metadata);
badArtifact.artifact.sha256 = 'not-a-sha256';
assert(rejects(badArtifact, 'artifact'), 'validator must reject a malformed artifact hash');

const staleArtifact = clone(metadata);
staleArtifact.artifact.byteLength += 1;
assert(rejects(staleArtifact, 'artifact byte length'), 'validator must reject stale artifact bytes');

const badDistribution = clone(metadata);
badDistribution.distribution.source.branch = 'gh-pages';
assert(rejects(badDistribution, 'distribution.source'), 'validator must reject a noncanonical Pages source');

const badEvidence = clone(metadata);
badEvidence.selection.farField.evidence = 'docs/development/missing.md';
assert(rejects(badEvidence, 'target does not exist'), 'validator must reject a missing evidence document');

const badAcceptance = clone(metadata);
badAcceptance.acceptance.samsungSmoothness.status = 'accepted';
assert(rejects(badAcceptance, 'acceptance.samsungSmoothness'), 'validator must reject an unsupported acceptance status');

console.log(JSON.stringify({
  check: 'project-metadata-truth',
  pass: true,
  commit: currentCommit,
  buildId: BASELINE.buildId,
  artifactSha256: artifact.sha256,
  distribution: `${distribution.source.branch}:${distribution.source.path}`,
  farField: farField.status,
  samsungSmoothness: samsung.status,
  userVisual: visual.status,
}));

